### ISSUE TITLE
選曲が変わった直後のミニプレイヤーでのTwitter共有に齟齬がでる

### ISSUE THREAD

**Issue by sarubo** [sevenc-nanashi/kiitecafe-desktop#1]
## 不具合の内容

選曲が変わった直後のミニプレイヤーでのTwitter共有をした際に、タイトルは現在選曲されている曲、urlとタグは直前に再生されていた曲が記述される。

### 現象・ログ

![image](https://user-images.githubusercontent.com/47109823/211971292-a6784174-1306-4640-a17d-10ac88de61f9.png)

実際にツイートされている方の例
https://twitter.com/vocaloidsongrt/status/1613367177159278594
https://twitter.com/vocaloidsongrt/status/1613367724935380992

### 再現手順

選曲が変わった直後のミニプレイヤーでのTwitter共有をする。

### 期待動作

タイトルとurlとタグは現在選曲されている曲が記述される。

### Kiite Cafe Desktopのバージョン

0.2.1

**Comment by sevenc-nanashi** [comment]
バグ報告ありがとうございます！

修正したいと思いますー。

**Comment by sevenc-nanashi** [comment]
[プレビュー版（v0.2.2-preview.0）](https://github.com/sevenc-nanashi/kiitecafe-desktop/releases/tag/v0.2.2-preview.0)作ってみました。直ってると思います。

**Comment by sarubo** [comment]
問題なく共有できているように見えました！修正ありがとうございました！
