### ISSUE TITLE
自動リロード回数の制限

### ISSUE THREAD

**Issue by mitac-31709** [sevenc-nanashi/kiitecafe-desktop#6]
ニコニコ動画のサーバーが停止し動画が再生できなかった際に、リロード回数の制限がないと常にリロードされ続けます。
まともに会話ができません(そんな事ある？)

**Comment by sevenc-nanashi** [comment]
そもそもニコニコのサーバーが落ちてるケースがレアケースなのでブラウザ使ってください（申し訳ない）
